### ISSUE TITLE
A doubt regarding the test data.

### ISSUE THREAD

**Issue by Hsankesara** [renmengye/few-shot-ssl-public#10]
Hey @renmengye,
I have a doubt regarding the paper. Suppose we trained the model by taking 5 classes in each episode. I have total of 40 classes. After training, I have test data where I have to classify each image to one of the 40 categories. Now how can I do that? The most logical way is to calculate a noormalized probability for each class and then assigned an image to a class with the highest probability. But this somehow looks not the right way as we trained the model for only 5 classes. Kindly help me here
Regards

**Comment by Duan-JM** [comment]
During the test stage, if u select 5 way, it means that the unlabeled query samples are in this 5 way. For each episode in the test, we still random pick novel classes.

**Comment by Hsankesara** [comment]
Thanks, @VDeamoV .
