### ISSUE TITLE
How to interpret the pkl files?

### ISSUE THREAD

**Issue by purboo** [renmengye/few-shot-ssl-public#5]
I read the files with the following codes:

```
import pickle as pkl

with open("val_images_png.pkl", "rb") as f:
    data = pkl.load(f)
```

Then I found that `data` is a list of (n, 1) arrays. For example, 

```
print(data[0].shape) # (18068, 1)
```

I think each array corresponds to an image. However, `18068` is not even divisible by 3, which means that it is not an RGB image? 

How could I convert each array to an image with shape (H, W, 3)? Thanks.

**Comment by renmengye** [comment]
This is the PNG binary encoding of the image.

**Comment by purboo** [comment]
@renmengye Then how to save the binary encoding to a png file? Thanks.

**Comment by renmengye** [comment]
There is a helper file here: https://github.com/renmengye/few-shot-ssl-public/blob/master/fewshot/data/compress_tiered_imagenet.py

**Comment by purboo** [comment]
Thanks a lot!
